from enum import Enum
class Direction(Enum):
    RIGHT = -1
    LEFT = 1

class Layer(Enum):
    LOWER = 0
    UPPER = 1

class FiniteState(Enum):
    IDLE = 0
    ORIGIN_POSITION_TO_PICKING_POSITION = 1
    DECREASING_JOINT3_AND_JOINT5 = 2
    WAITING_DECREASING_JOINT3_AND_JOINT5 = 3
    JOINT1_TURNING = 4
    WAITING_JOINT1_TURNING = 5
    LIFTING_JOINT3 = 6
    WAITING_LIFTING_JOINT3 = 7
    PICKING_POSITION_TO_PRE_PLACING_POSITION = 8
    ROTATING_JOINT1_TO_FRONT = 9
    WAITING_ROTATING_JOINT1_TO_FRONT = 10
    PRE_PLACING_POSITION_TO_PLACING_POSITION = 11
    PLACING_AT_LAYER = 12
    PLACING_AT_UPPER_LAYER = 13
    JOINT2_JOINT3_TO_UPPER_LAYER = 14
    WAITING_JOINT2_JOINT3_TO_UPPER_LAYER = 15
    JOINT3_TO_UPPER_LAYER = 16
    WAITING_JOINT3_TO_UPPER_LAYER = 17
    PLACING_POSITION_TO_PRE_ORIGIN_POSITION = 97
    PLACING_POSITION_TO_ORIGIN_POSITION = 98
    RESETTING_ALL_JOINTS = 99